version: '2.1'
services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:9.4.5
    env_file:
      - ./api/.env.prod
    volumes:
      - /var/lib/postgresql/9.5/main:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "psql -h localhost -p 5432 -U postgres -v ON_ERROR_STOP=1 -c 'select version()' &> /dev/null"]
        test: ["CMD-SHELL", "pg_isready -U postgres"] #Are you really up?
        interval: 2s
        timeout: 30s
        retries: 15
  api:
    build:
      context: ./api
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./api/.env.prod
    tty: true
    stdin_open: true
    ports:
     - 4000:4000
    labels:
      - traefik.http.routers.api.rule=Host(`api.pomodoro.works`)
      - traefik.protocol=https
      #- traefik.http.services.apiali.loadbalancer.healthcheck.hostname=dev-api.pomodoro.works
      #- traefik.http.services.apiali.loadbalancer.healthcheck.path=/health-check
      #- traefik.http.services.apiali.loadbalancer.healthcheck.interval=30s
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=myresolver
  app:
    tty: true
    ports:
      - "3000:80"
    build:
      context: ./app
      dockerfile: Dockerfile_production
    tty: true
    stdin_open: true
    labels:
      - traefik.http.routers.app.rule=Host(`pomodoro.works`)
      - traefik.protocol=https
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=myresolver
